### ISSUE TITLE
Placing with offhand takes two blocks instead of one

### ISSUE THREAD

**Issue by M-ag-e** [DriHut/ReFramed#13]
Minecraft Version: 1.20.1
Mod Version: 1.5.9 (Modrinth)
Fabric Version: 0.15.11
Fabric API Version: 0.92.2+1.20.1

When placing blocks that are in your off hand it takes two blocks but only places one.
I think the mechanic when you place a frame with blocks in your off hand and the frame takes the blocks appearance is broken and is applying all the time and not just when a frame is held.
I tested this in a fresh install with just ReFramed installed (and its Fabric + API) and got the same issue.

**Comment by DriHut** [comment]
Thank you for the feedback I've corrected the issue and will make a new version with the fix publicly available soon. If you wanted to know I wasn't checking correctly if a frame was in the main hand making it remove blocks even when not using a frame ^^.
