### ISSUE TITLE
pillars wall frame crash bug

### ISSUE THREAD

**Issue by MGjokern** [DriHut/ReFramed#14]
Hey i was decorating using the "pillars wall frame" with a oak log as a center and flowering azalea leaves as inbetwen a normal wall frame with flowering azalea leaves. the scekent i put the leaves in the pillars wall frame it insta crashed i testede it in a test world and the same thing happend. now both world are locked in a insta crash loop.

i hope you are still working on the mod and if so that my exolanation is of help.

[crash-2024-07-01_00.22.17-client.txt](https://github.com/user-attachments/files/16046407/crash-2024-07-01_00.22.17-client.txt)

**Comment by DriHut** [comment]
Hi thanks for the feedback I'll do a quick fix and release it in a subversion so that you can start playing on your world again (actually nvm found the issue ^^ fix will be there when I'm done with the new additions e.g. hopefully in less than 24h)

**Comment by DriHut** [comment]
The fix has been released with version 1.6.6. Enjoy!
