### ISSUE TITLE
Fabric loader v15.3 1.19.2 Support

### ISSUE THREAD

**Issue by HeadSetHero80** [DriHut/ReFramed#15]
Hello,

I'm currently using Minecraft version 1.19.2 for my mod pack, and I've encountered issues with the Copycat+ mod. Then I Remembered the Framed Blocks mod. I would appreciate it if you could make this project to be compatible with version 1.19.2.

Thank you!

**Comment by DriHut** [comment]
Hi, 

I'm very sorry. But 1.19.2 is too different from 1.20.x in terms of rendering. That coupled with the fact that I'm very busy I won't be doing it. 
(Plus I currently working on the slopes so it's not the priority). Of course you can always ask someone or fork it yourself.

**Comment by HeadSetHero80** [comment]
ok i understand gl!

**Comment by quentinlegot** [comment]
Reopen it if you still need help
