### ISSUE TITLE
ReFramed breaks Spectrum's Block Placer

### ISSUE THREAD

**Issue by anarchy-chan** [DriHut/ReFramed#21]
Minecraft: 1.20.1 (Fabric 0.16.5)
ReFramed: All 1.20.1 releases
Spectrum: 1.7.16-deeper-down

Having ReFramed installed alongside [Spectrum](https://modrinth.com/mod/spectrum) causes the `spectrum:block_placer` to not consume placed blocks from the block entity's inventory.

How to reproduce:
1. Install Spectrum and ReFramed
2. Place a `spectrum:block_placer` on the ground and fill it with any block (e.g. dirt)
3. Power the Block Placer with a redstone signal

This might be related to #19 or `BlockItemMixin.java` in general.

**Comment by DriHut** [comment]
It is indeed that same issue ^^

**Comment by anarchy-chan** [comment]
Alright, thank you!
