### ISSUE TITLE
Lighter frames showing up as invisible?

### ISSUE THREAD

**Issue by Dumpling00** [DriHut/ReFramed#4]
Hello! Big fan of your mod here. I'm having this peculiar issue when placing the clear looking frames. I'm on Fabric 1.20.4.
Could this be looked into?

https://github.com/DriHut/ReFramed/assets/44829013/4ca15e2c-cd06-4efb-a3e2-d3b9ab09593f

Thanks for your time!

**Comment by DriHut** [comment]
From what I see you are using iris with it. It could be iris or it could be another mod so if you can give me a list of the mods you have or try removing some mods till you find the one that is problematic. Then I can maybe figure out a fix for it ^^.

**Comment by Dumpling00** [comment]
> From what I see you are using iris with it. It could be iris or it could be another mod so if you can give me a list of the mods you have or try removing some mods till you find the one that is problematic. Then I can maybe figure out a fix for it ^^.

Hi! Unfortunately I have at least a hundred other mods so it's gonna be a bit tricky to find the culprit haha.
Would you know which kind of mod could be the cause of this? Anything that touches graphical rendering I'm guessing?

**Comment by DriHut** [comment]
Yes any mod that add rendering so that's why I mentioned iris. Maybe if you add a list of the mods I can already cross out the ones that shouldn't be causing this issue.

**Comment by Dumpling00** [comment]
> Yes any mod that add rendering so that's why I mentioned iris. Maybe if you add a list of the mods I can already cross out the ones that shouldn't be causing this issue.

Okay I just checked and I have 311 mods installed, so a bit more than 100 lol.
But here, I've tried with a new instance (basically unmodded) and everything looks great. (Fabric 1.20.4 btw)

Added Iris, and this happens:
![image](https://github.com/DriHut/ReFramed/assets/44829013/cc18745e-0d89-40ee-9b09-779565cf7f45)

Added Indium on top, and we're back to this
![image](https://github.com/DriHut/ReFramed/assets/44829013/8865bffa-89b4-45a3-befe-3864308f5598)

Added Entity Culling, Continuity, Fusion (Connected Textures) and Ferrite Core - No changes
Tried with Shaders on - No changes

And now I had a thought - could it be the texture packs? Turns out, these are the issue:
![image](https://github.com/DriHut/ReFramed/assets/44829013/30e9e8d2-a56a-4759-b234-9e5cc6195a9d)

How it looks with xali's texture pack only:
![image](https://github.com/DriHut/ReFramed/assets/44829013/0f79cd0a-ec7c-49b1-92fd-0caa8c29c8b4)

How it looks with Glass Pane Culling Fix only:
![image](https://github.com/DriHut/ReFramed/assets/44829013/9ec46e3b-8ce2-4114-a55b-1af6d497b4f1)

How it looks with all three together:
![image](https://github.com/DriHut/ReFramed/assets/44829013/5e1e6524-553c-4b3c-b0b3-ad7bfd9b42e4)

Issue persists when disabling the resource packs.
![image](https://github.com/DriHut/ReFramed/assets/44829013/edc87cc5-40fd-4fd5-b85e-c4f1d95cfda2)

Various degrees of results depending on the order, it seems.

Hope this helps! Thank you in advance for your time!

**Comment by DriHut** [comment]
Ooooh now I might know why it does this 😅. I'm pretty sure that if you reload the game when you add the texture pack this will work as in it might be due to the remapping of the atlas but since I keep those in cache it still tries to take the texture at the same place on the atlas hence why it looks like this. So I don't think that's why it wasn't working in the first place but that is an issue I need to fix too 😅.

Also thank you for taking the time to figure out what is wrong 🙏.

**Comment by DriHut** [comment]
![image](https://github.com/DriHut/ReFramed/assets/63098227/dc4e4c42-d0b6-4a72-abd2-e56ba93c94e0)
![image](https://github.com/DriHut/ReFramed/assets/63098227/0f403626-ca0e-42a3-833c-0c672cde4acd)

I just tried it and it seems to be exactly what I though the fixt will be quite easy to implement. (for context I used the top block as a theme first then loaded the texture pack then used the second block) so when I remove the texture pack the top is good and bottom wrong ^^.

**Comment by Dumpling00** [comment]
Awesome to hear! Can't wait to test out the new version.
Thank you for your efforts :)

**Comment by DriHut** [comment]
Yeah well I still think the first error you showed wasn't due to this...

**Comment by Dumpling00** [comment]
> Yeah well I still think the first error you showed wasn't due to this...

Seems like that can be fixed by simply listing indium as another dependency for iris users though! Albeit being not exactly a dependency, it does seem to counter the issue.

**Comment by DriHut** [comment]
oh so you weren't using indium at the beginning ? cuz if yes then its normal that it breaks as the mod needs indium if there is sodium installed and iris uses sodium.

**Comment by Dumpling00** [comment]
I can also confirm that this issue is indeed caused by Continuity's Default Connected Textures.

![image](https://github.com/DriHut/ReFramed/assets/44829013/7c6390e7-cc1c-4c63-9d73-5baad91a52f3)

Applying a cube to frames that are rendered invisible because of this causes the void to appear.
Doesn't happen with Glass Pane Culling Fix enabled on its own.

**Comment by Dumpling00** [comment]
> oh so you weren't using indium at the beginning ? cuz if yes then its normal that it breaks as the mod needs indium if there is sodium installed and iris uses sodium.

Nope! The first image with the null blocks happens with Iris/Sodium only. Adding Indium fixes the issue.

**Comment by DriHut** [comment]
> I can also confirm that this issue is indeed caused by Continuity's Default Connected Textures.
> ...

Yeah that sounds pretty likely continuity probably inject in the rendering of their textures before my code is injected hence why it breaks with it. Though I might add full support for Continuity anyway. Also the side is invisible probably because it still computes the cull even though its not being rendered.

**Comment by DriHut** [comment]
> Nope! The first image with the null blocks happens with Iris/Sodium only. Adding Indium fixes the issue.

Ok  nice that this was the issue ^^. (less for me to fix ;-) ) Please make sure you always use indium when you have sodium installed.

**Comment by Dumpling00** [comment]
> > I can also confirm that this issue is indeed caused by Continuity's Default Connected Textures.
> > ...
> 
> Yeah that sounds pretty likely continuity probably inject in the rendering of their textures before my code is injected hence why it breaks with it. Though I might add full support for Continuity anyway. Also the side is invisible probably because it still computes the cull even though its not being rendered.

Yeah I've encountered similar issues before so I figured! It was a fun hunt though, glad I could help.
Good luck with your endeavors!

**Comment by DriHut** [comment]
Thanks for the feedback always appreciated ^^
